import React from "react";
import type {Metadata} from "next";
import "./globals.css";
import {Header} from "@/components/layout/header";
import {Footer} from "@/components/layout/footer";

export const metadata: Metadata = {
    title: "UMI01",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`min-h-full antialiased`}>
        <div className={'h-screen grid grid-rows-[56px_1fr_30px] md:grid-rows-[100px_1fr_30px]'}>
            <Header/>
            <main className={'w-full mx-auto md:px-7.5'}>
                {children}
            </main>
            <Footer/>
        </div>
        </body>
        </html>
    );
}
